project:
  type: website
  output-dir: docs

# Meta
description-meta: "Lingwei's Homepage"
author-meta: "Lingwei Zheng"

website:
  title: "Sensing Urban Dynamics"
  image: "files/profiles/profile2.jpg"
  description: "Lingwei's Homepage"
 
  navbar:
    background: light

    left:
      - text: Posts
        menu:
          - text: Events
            href: posts.qmd#category=event
          - text: Presentation
            href: posts.qmd#category=talk
          - text: Recent papers
            href: posts.qmd#category=paper
          - text: All posts
            href: posts.qmd
      # - text: Home
      #   href: index.qmd
      - text: Publication
        href: publications.qmd
          # - text: Selected Papers
          #   href: posts.qmd#category=paper
          # - text: Grants
          #   href: projects.qmd                                
      - text: Presentation
        href: presentation.qmd
      - text: Teaching & Services
        href: teaching.qmd
      - text: Contact
        href: contact.qmd 
      # - text: Outreach
      #   menu:        
      #   - text: Presentations
      #     href: posts.qmd#category=presentation                   
      # - text: Group
      #   href: people.qmd

    right: 
      - text: CV
        href: files/Lingwei_s_Resume.pdf
      - icon: github
        href: https://github.com/lingwei-zheng
        target: _blank
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Lingwei-Zheng-3?ev=hdr_xprf
        target: _blank   
      - text: "{{< fa brands x-twitter >}}"
        href: https://x.com/LingweiZheng
        target: _blank      
  
  page-navigation: true
  
  page-footer: 
    left: "[Lingwei Zheng](http://lingwei-zheng.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:  
      - icon: github
        href: https://github.com/lingwei-zheng
        target: _blank
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Lingwei-Zheng-3?ev=hdr_xprf
        target: _blank
      - text: "{{< fa brands x-twitter >}}" 
        href: https://x.com/LingweiZheng
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/lingwei-zheng/lingwei-zheng.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://lingwei-zheng.github.io"
  
  google-analytics:
    tracking-id: "G-14EQZPM1N7"  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

